HEADERS += \
    $$PWD/ComThread.h \
    $$PWD/ROS/ros_lib/actionlib/TestAction.h \
    $$PWD/ROS/ros_lib/actionlib/TestActionFeedback.h \
    $$PWD/ROS/ros_lib/actionlib/TestActionGoal.h \
    $$PWD/ROS/ros_lib/actionlib/TestActionResult.h \
    $$PWD/ROS/ros_lib/actionlib/TestFeedback.h \
    $$PWD/ROS/ros_lib/actionlib/TestGoal.h \
    $$PWD/ROS/ros_lib/actionlib/TestRequestAction.h \
    $$PWD/ROS/ros_lib/actionlib/TestRequestActionFeedback.h \
    $$PWD/ROS/ros_lib/actionlib/TestRequestActionGoal.h \
    $$PWD/ROS/ros_lib/actionlib/TestRequestActionResult.h \
    $$PWD/ROS/ros_lib/actionlib/TestRequestFeedback.h \
    $$PWD/ROS/ros_lib/actionlib/TestRequestGoal.h \
    $$PWD/ROS/ros_lib/actionlib/TestRequestResult.h \
    $$PWD/ROS/ros_lib/actionlib/TestResult.h \
    $$PWD/ROS/ros_lib/actionlib/TwoIntsAction.h \
    $$PWD/ROS/ros_lib/actionlib/TwoIntsActionFeedback.h \
    $$PWD/ROS/ros_lib/actionlib/TwoIntsActionGoal.h \
    $$PWD/ROS/ros_lib/actionlib/TwoIntsActionResult.h \
    $$PWD/ROS/ros_lib/actionlib/TwoIntsFeedback.h \
    $$PWD/ROS/ros_lib/actionlib/TwoIntsGoal.h \
    $$PWD/ROS/ros_lib/actionlib/TwoIntsResult.h \
    $$PWD/ROS/ros_lib/actionlib_msgs/GoalID.h \
    $$PWD/ROS/ros_lib/actionlib_msgs/GoalStatus.h \
    $$PWD/ROS/ros_lib/actionlib_msgs/GoalStatusArray.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/AveragingAction.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/AveragingActionFeedback.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/AveragingActionGoal.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/AveragingActionResult.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/AveragingFeedback.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/AveragingGoal.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/AveragingResult.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/FibonacciAction.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/FibonacciActionFeedback.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/FibonacciActionGoal.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/FibonacciActionResult.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/FibonacciFeedback.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/FibonacciGoal.h \
    $$PWD/ROS/ros_lib/actionlib_tutorials/FibonacciResult.h \
    $$PWD/ROS/ros_lib/bond/Constants.h \
    $$PWD/ROS/ros_lib/bond/Status.h \
    $$PWD/ROS/ros_lib/control_msgs/FollowJointTrajectoryAction.h \
    $$PWD/ROS/ros_lib/control_msgs/FollowJointTrajectoryActionFeedback.h \
    $$PWD/ROS/ros_lib/control_msgs/FollowJointTrajectoryActionGoal.h \
    $$PWD/ROS/ros_lib/control_msgs/FollowJointTrajectoryActionResult.h \
    $$PWD/ROS/ros_lib/control_msgs/FollowJointTrajectoryFeedback.h \
    $$PWD/ROS/ros_lib/control_msgs/FollowJointTrajectoryGoal.h \
    $$PWD/ROS/ros_lib/control_msgs/FollowJointTrajectoryResult.h \
    $$PWD/ROS/ros_lib/control_msgs/GripperCommand.h \
    $$PWD/ROS/ros_lib/control_msgs/GripperCommandAction.h \
    $$PWD/ROS/ros_lib/control_msgs/GripperCommandActionFeedback.h \
    $$PWD/ROS/ros_lib/control_msgs/GripperCommandActionGoal.h \
    $$PWD/ROS/ros_lib/control_msgs/GripperCommandActionResult.h \
    $$PWD/ROS/ros_lib/control_msgs/GripperCommandFeedback.h \
    $$PWD/ROS/ros_lib/control_msgs/GripperCommandGoal.h \
    $$PWD/ROS/ros_lib/control_msgs/GripperCommandResult.h \
    $$PWD/ROS/ros_lib/control_msgs/JointControllerState.h \
    $$PWD/ROS/ros_lib/control_msgs/JointJog.h \
    $$PWD/ROS/ros_lib/control_msgs/JointTolerance.h \
    $$PWD/ROS/ros_lib/control_msgs/JointTrajectoryAction.h \
    $$PWD/ROS/ros_lib/control_msgs/JointTrajectoryActionFeedback.h \
    $$PWD/ROS/ros_lib/control_msgs/JointTrajectoryActionGoal.h \
    $$PWD/ROS/ros_lib/control_msgs/JointTrajectoryActionResult.h \
    $$PWD/ROS/ros_lib/control_msgs/JointTrajectoryControllerState.h \
    $$PWD/ROS/ros_lib/control_msgs/JointTrajectoryFeedback.h \
    $$PWD/ROS/ros_lib/control_msgs/JointTrajectoryGoal.h \
    $$PWD/ROS/ros_lib/control_msgs/JointTrajectoryResult.h \
    $$PWD/ROS/ros_lib/control_msgs/PidState.h \
    $$PWD/ROS/ros_lib/control_msgs/PointHeadAction.h \
    $$PWD/ROS/ros_lib/control_msgs/PointHeadActionFeedback.h \
    $$PWD/ROS/ros_lib/control_msgs/PointHeadActionGoal.h \
    $$PWD/ROS/ros_lib/control_msgs/PointHeadActionResult.h \
    $$PWD/ROS/ros_lib/control_msgs/PointHeadFeedback.h \
    $$PWD/ROS/ros_lib/control_msgs/PointHeadGoal.h \
    $$PWD/ROS/ros_lib/control_msgs/PointHeadResult.h \
    $$PWD/ROS/ros_lib/control_msgs/QueryCalibrationState.h \
    $$PWD/ROS/ros_lib/control_msgs/QueryTrajectoryState.h \
    $$PWD/ROS/ros_lib/control_msgs/SingleJointPositionAction.h \
    $$PWD/ROS/ros_lib/control_msgs/SingleJointPositionActionFeedback.h \
    $$PWD/ROS/ros_lib/control_msgs/SingleJointPositionActionGoal.h \
    $$PWD/ROS/ros_lib/control_msgs/SingleJointPositionActionResult.h \
    $$PWD/ROS/ros_lib/control_msgs/SingleJointPositionFeedback.h \
    $$PWD/ROS/ros_lib/control_msgs/SingleJointPositionGoal.h \
    $$PWD/ROS/ros_lib/control_msgs/SingleJointPositionResult.h \
    $$PWD/ROS/ros_lib/control_toolbox/SetPidGains.h \
    $$PWD/ROS/ros_lib/controller_manager_msgs/ControllerState.h \
    $$PWD/ROS/ros_lib/controller_manager_msgs/ControllerStatistics.h \
    $$PWD/ROS/ros_lib/controller_manager_msgs/ControllersStatistics.h \
    $$PWD/ROS/ros_lib/controller_manager_msgs/HardwareInterfaceResources.h \
    $$PWD/ROS/ros_lib/controller_manager_msgs/ListControllerTypes.h \
    $$PWD/ROS/ros_lib/controller_manager_msgs/ListControllers.h \
    $$PWD/ROS/ros_lib/controller_manager_msgs/LoadController.h \
    $$PWD/ROS/ros_lib/controller_manager_msgs/ReloadControllerLibraries.h \
    $$PWD/ROS/ros_lib/controller_manager_msgs/SwitchController.h \
    $$PWD/ROS/ros_lib/controller_manager_msgs/UnloadController.h \
    $$PWD/ROS/ros_lib/diagnostic_msgs/AddDiagnostics.h \
    $$PWD/ROS/ros_lib/diagnostic_msgs/DiagnosticArray.h \
    $$PWD/ROS/ros_lib/diagnostic_msgs/DiagnosticStatus.h \
    $$PWD/ROS/ros_lib/diagnostic_msgs/KeyValue.h \
    $$PWD/ROS/ros_lib/diagnostic_msgs/SelfTest.h \
    $$PWD/ROS/ros_lib/dynamic_reconfigure/BoolParameter.h \
    $$PWD/ROS/ros_lib/dynamic_reconfigure/Config.h \
    $$PWD/ROS/ros_lib/dynamic_reconfigure/ConfigDescription.h \
    $$PWD/ROS/ros_lib/dynamic_reconfigure/DoubleParameter.h \
    $$PWD/ROS/ros_lib/dynamic_reconfigure/Group.h \
    $$PWD/ROS/ros_lib/dynamic_reconfigure/GroupState.h \
    $$PWD/ROS/ros_lib/dynamic_reconfigure/IntParameter.h \
    $$PWD/ROS/ros_lib/dynamic_reconfigure/ParamDescription.h \
    $$PWD/ROS/ros_lib/dynamic_reconfigure/Reconfigure.h \
    $$PWD/ROS/ros_lib/dynamic_reconfigure/SensorLevels.h \
    $$PWD/ROS/ros_lib/dynamic_reconfigure/StrParameter.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/ApplyBodyWrench.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/ApplyJointEffort.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/BodyRequest.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/ContactState.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/ContactsState.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/DeleteLight.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/DeleteModel.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/GetJointProperties.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/GetLightProperties.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/GetLinkProperties.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/GetLinkState.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/GetModelProperties.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/GetModelState.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/GetPhysicsProperties.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/GetWorldProperties.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/JointRequest.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/LinkState.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/LinkStates.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/ModelState.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/ModelStates.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/ODEJointProperties.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/ODEPhysics.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/SetJointProperties.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/SetJointTrajectory.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/SetLightProperties.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/SetLinkProperties.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/SetLinkState.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/SetModelConfiguration.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/SetModelState.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/SetPhysicsProperties.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/SpawnModel.h \
    $$PWD/ROS/ros_lib/gazebo_msgs/WorldState.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Accel.h \
    $$PWD/ROS/ros_lib/geometry_msgs/AccelStamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/AccelWithCovariance.h \
    $$PWD/ROS/ros_lib/geometry_msgs/AccelWithCovarianceStamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Inertia.h \
    $$PWD/ROS/ros_lib/geometry_msgs/InertiaStamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Point.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Point32.h \
    $$PWD/ROS/ros_lib/geometry_msgs/PointStamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Polygon.h \
    $$PWD/ROS/ros_lib/geometry_msgs/PolygonStamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Pose.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Pose2D.h \
    $$PWD/ROS/ros_lib/geometry_msgs/PoseArray.h \
    $$PWD/ROS/ros_lib/geometry_msgs/PoseStamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/PoseWithCovariance.h \
    $$PWD/ROS/ros_lib/geometry_msgs/PoseWithCovarianceStamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Quaternion.h \
    $$PWD/ROS/ros_lib/geometry_msgs/QuaternionStamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Transform.h \
    $$PWD/ROS/ros_lib/geometry_msgs/TransformStamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Twist.h \
    $$PWD/ROS/ros_lib/geometry_msgs/TwistStamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/TwistWithCovariance.h \
    $$PWD/ROS/ros_lib/geometry_msgs/TwistWithCovarianceStamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Vector3.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Vector3Stamped.h \
    $$PWD/ROS/ros_lib/geometry_msgs/Wrench.h \
    $$PWD/ROS/ros_lib/geometry_msgs/WrenchStamped.h \
    $$PWD/ROS/ros_lib/laser_assembler/AssembleScans.h \
    $$PWD/ROS/ros_lib/laser_assembler/AssembleScans2.h \
    $$PWD/ROS/ros_lib/map_msgs/GetMapROI.h \
    $$PWD/ROS/ros_lib/map_msgs/GetPointMap.h \
    $$PWD/ROS/ros_lib/map_msgs/GetPointMapROI.h \
    $$PWD/ROS/ros_lib/map_msgs/OccupancyGridUpdate.h \
    $$PWD/ROS/ros_lib/map_msgs/PointCloud2Update.h \
    $$PWD/ROS/ros_lib/map_msgs/ProjectedMap.h \
    $$PWD/ROS/ros_lib/map_msgs/ProjectedMapInfo.h \
    $$PWD/ROS/ros_lib/map_msgs/ProjectedMapsInfo.h \
    $$PWD/ROS/ros_lib/map_msgs/SaveMap.h \
    $$PWD/ROS/ros_lib/map_msgs/SetMapProjections.h \
    $$PWD/ROS/ros_lib/nav_msgs/GetMap.h \
    $$PWD/ROS/ros_lib/nav_msgs/GetMapAction.h \
    $$PWD/ROS/ros_lib/nav_msgs/GetMapActionFeedback.h \
    $$PWD/ROS/ros_lib/nav_msgs/GetMapActionGoal.h \
    $$PWD/ROS/ros_lib/nav_msgs/GetMapActionResult.h \
    $$PWD/ROS/ros_lib/nav_msgs/GetMapFeedback.h \
    $$PWD/ROS/ros_lib/nav_msgs/GetMapGoal.h \
    $$PWD/ROS/ros_lib/nav_msgs/GetMapResult.h \
    $$PWD/ROS/ros_lib/nav_msgs/GetPlan.h \
    $$PWD/ROS/ros_lib/nav_msgs/GridCells.h \
    $$PWD/ROS/ros_lib/nav_msgs/MapMetaData.h \
    $$PWD/ROS/ros_lib/nav_msgs/OccupancyGrid.h \
    $$PWD/ROS/ros_lib/nav_msgs/Odometry.h \
    $$PWD/ROS/ros_lib/nav_msgs/Path.h \
    $$PWD/ROS/ros_lib/nav_msgs/SetMap.h \
    $$PWD/ROS/ros_lib/nodelet/NodeletList.h \
    $$PWD/ROS/ros_lib/nodelet/NodeletLoad.h \
    $$PWD/ROS/ros_lib/nodelet/NodeletUnload.h \
    $$PWD/ROS/ros_lib/pcl_msgs/ModelCoefficients.h \
    $$PWD/ROS/ros_lib/pcl_msgs/PointIndices.h \
    $$PWD/ROS/ros_lib/pcl_msgs/PolygonMesh.h \
    $$PWD/ROS/ros_lib/pcl_msgs/Vertices.h \
    $$PWD/ROS/ros_lib/polled_camera/GetPolledImage.h \
    $$PWD/ROS/ros_lib/ros/duration.h \
    $$PWD/ROS/ros_lib/ros/msg.h \
    $$PWD/ROS/ros_lib/ros/node_handle.h \
    $$PWD/ROS/ros_lib/ros/publisher.h \
    $$PWD/ROS/ros_lib/ros/service_client.h \
    $$PWD/ROS/ros_lib/ros/service_server.h \
    $$PWD/ROS/ros_lib/ros/subscriber.h \
    $$PWD/ROS/ros_lib/ros/time.h \
    $$PWD/ROS/ros_lib/roscpp/Empty.h \
    $$PWD/ROS/ros_lib/roscpp/GetLoggers.h \
    $$PWD/ROS/ros_lib/roscpp/Logger.h \
    $$PWD/ROS/ros_lib/roscpp/SetLoggerLevel.h \
    $$PWD/ROS/ros_lib/roscpp_tutorials/TwoInts.h \
    $$PWD/ROS/ros_lib/rosgraph_msgs/Clock.h \
    $$PWD/ROS/ros_lib/rosgraph_msgs/Log.h \
    $$PWD/ROS/ros_lib/rosgraph_msgs/TopicStatistics.h \
    $$PWD/ROS/ros_lib/rospy_tutorials/AddTwoInts.h \
    $$PWD/ROS/ros_lib/rospy_tutorials/BadTwoInts.h \
    $$PWD/ROS/ros_lib/rospy_tutorials/Floats.h \
    $$PWD/ROS/ros_lib/rospy_tutorials/HeaderString.h \
    $$PWD/ROS/ros_lib/rosserial_msgs/Log.h \
    $$PWD/ROS/ros_lib/rosserial_msgs/RequestMessageInfo.h \
    $$PWD/ROS/ros_lib/rosserial_msgs/RequestParam.h \
    $$PWD/ROS/ros_lib/rosserial_msgs/RequestServiceInfo.h \
    $$PWD/ROS/ros_lib/rosserial_msgs/TopicInfo.h \
    $$PWD/ROS/ros_lib/sensor_msgs/BatteryState.h \
    $$PWD/ROS/ros_lib/sensor_msgs/CameraInfo.h \
    $$PWD/ROS/ros_lib/sensor_msgs/ChannelFloat32.h \
    $$PWD/ROS/ros_lib/sensor_msgs/CompressedImage.h \
    $$PWD/ROS/ros_lib/sensor_msgs/FluidPressure.h \
    $$PWD/ROS/ros_lib/sensor_msgs/Illuminance.h \
    $$PWD/ROS/ros_lib/sensor_msgs/Image.h \
    $$PWD/ROS/ros_lib/sensor_msgs/Imu.h \
    $$PWD/ROS/ros_lib/sensor_msgs/JointState.h \
    $$PWD/ROS/ros_lib/sensor_msgs/Joy.h \
    $$PWD/ROS/ros_lib/sensor_msgs/JoyFeedback.h \
    $$PWD/ROS/ros_lib/sensor_msgs/JoyFeedbackArray.h \
    $$PWD/ROS/ros_lib/sensor_msgs/LaserEcho.h \
    $$PWD/ROS/ros_lib/sensor_msgs/LaserScan.h \
    $$PWD/ROS/ros_lib/sensor_msgs/MagneticField.h \
    $$PWD/ROS/ros_lib/sensor_msgs/MultiDOFJointState.h \
    $$PWD/ROS/ros_lib/sensor_msgs/MultiEchoLaserScan.h \
    $$PWD/ROS/ros_lib/sensor_msgs/NavSatFix.h \
    $$PWD/ROS/ros_lib/sensor_msgs/NavSatStatus.h \
    $$PWD/ROS/ros_lib/sensor_msgs/PointCloud.h \
    $$PWD/ROS/ros_lib/sensor_msgs/PointCloud2.h \
    $$PWD/ROS/ros_lib/sensor_msgs/PointField.h \
    $$PWD/ROS/ros_lib/sensor_msgs/Range.h \
    $$PWD/ROS/ros_lib/sensor_msgs/RegionOfInterest.h \
    $$PWD/ROS/ros_lib/sensor_msgs/RelativeHumidity.h \
    $$PWD/ROS/ros_lib/sensor_msgs/SetCameraInfo.h \
    $$PWD/ROS/ros_lib/sensor_msgs/Temperature.h \
    $$PWD/ROS/ros_lib/sensor_msgs/TimeReference.h \
    $$PWD/ROS/ros_lib/shape_msgs/Mesh.h \
    $$PWD/ROS/ros_lib/shape_msgs/MeshTriangle.h \
    $$PWD/ROS/ros_lib/shape_msgs/Plane.h \
    $$PWD/ROS/ros_lib/shape_msgs/SolidPrimitive.h \
    $$PWD/ROS/ros_lib/smach_msgs/SmachContainerInitialStatusCmd.h \
    $$PWD/ROS/ros_lib/smach_msgs/SmachContainerStatus.h \
    $$PWD/ROS/ros_lib/smach_msgs/SmachContainerStructure.h \
    $$PWD/ROS/ros_lib/std_msgs/Bool.h \
    $$PWD/ROS/ros_lib/std_msgs/Byte.h \
    $$PWD/ROS/ros_lib/std_msgs/ByteMultiArray.h \
    $$PWD/ROS/ros_lib/std_msgs/Char.h \
    $$PWD/ROS/ros_lib/std_msgs/ColorRGBA.h \
    $$PWD/ROS/ros_lib/std_msgs/Duration.h \
    $$PWD/ROS/ros_lib/std_msgs/Empty.h \
    $$PWD/ROS/ros_lib/std_msgs/Float32.h \
    $$PWD/ROS/ros_lib/std_msgs/Float32MultiArray.h \
    $$PWD/ROS/ros_lib/std_msgs/Float64.h \
    $$PWD/ROS/ros_lib/std_msgs/Float64MultiArray.h \
    $$PWD/ROS/ros_lib/std_msgs/Header.h \
    $$PWD/ROS/ros_lib/std_msgs/Int16.h \
    $$PWD/ROS/ros_lib/std_msgs/Int16MultiArray.h \
    $$PWD/ROS/ros_lib/std_msgs/Int32.h \
    $$PWD/ROS/ros_lib/std_msgs/Int32MultiArray.h \
    $$PWD/ROS/ros_lib/std_msgs/Int64.h \
    $$PWD/ROS/ros_lib/std_msgs/Int64MultiArray.h \
    $$PWD/ROS/ros_lib/std_msgs/Int8.h \
    $$PWD/ROS/ros_lib/std_msgs/Int8MultiArray.h \
    $$PWD/ROS/ros_lib/std_msgs/MultiArrayDimension.h \
    $$PWD/ROS/ros_lib/std_msgs/MultiArrayLayout.h \
    $$PWD/ROS/ros_lib/std_msgs/String.h \
    $$PWD/ROS/ros_lib/std_msgs/Time.h \
    $$PWD/ROS/ros_lib/std_msgs/UInt16.h \
    $$PWD/ROS/ros_lib/std_msgs/UInt16MultiArray.h \
    $$PWD/ROS/ros_lib/std_msgs/UInt32.h \
    $$PWD/ROS/ros_lib/std_msgs/UInt32MultiArray.h \
    $$PWD/ROS/ros_lib/std_msgs/UInt64.h \
    $$PWD/ROS/ros_lib/std_msgs/UInt64MultiArray.h \
    $$PWD/ROS/ros_lib/std_msgs/UInt8.h \
    $$PWD/ROS/ros_lib/std_msgs/UInt8MultiArray.h \
    $$PWD/ROS/ros_lib/std_srvs/Empty.h \
    $$PWD/ROS/ros_lib/std_srvs/SetBool.h \
    $$PWD/ROS/ros_lib/std_srvs/Trigger.h \
    $$PWD/ROS/ros_lib/stereo_msgs/DisparityImage.h \
    $$PWD/ROS/ros_lib/tf/FrameGraph.h \
    $$PWD/ROS/ros_lib/tf/tf.h \
    $$PWD/ROS/ros_lib/tf/tfMessage.h \
    $$PWD/ROS/ros_lib/tf/transform_broadcaster.h \
    $$PWD/ROS/ros_lib/tf2_msgs/FrameGraph.h \
    $$PWD/ROS/ros_lib/tf2_msgs/LookupTransformAction.h \
    $$PWD/ROS/ros_lib/tf2_msgs/LookupTransformActionFeedback.h \
    $$PWD/ROS/ros_lib/tf2_msgs/LookupTransformActionGoal.h \
    $$PWD/ROS/ros_lib/tf2_msgs/LookupTransformActionResult.h \
    $$PWD/ROS/ros_lib/tf2_msgs/LookupTransformFeedback.h \
    $$PWD/ROS/ros_lib/tf2_msgs/LookupTransformGoal.h \
    $$PWD/ROS/ros_lib/tf2_msgs/LookupTransformResult.h \
    $$PWD/ROS/ros_lib/tf2_msgs/TF2Error.h \
    $$PWD/ROS/ros_lib/tf2_msgs/TFMessage.h \
    $$PWD/ROS/ros_lib/theora_image_transport/Packet.h \
    $$PWD/ROS/ros_lib/topic_tools/DemuxAdd.h \
    $$PWD/ROS/ros_lib/topic_tools/DemuxDelete.h \
    $$PWD/ROS/ros_lib/topic_tools/DemuxList.h \
    $$PWD/ROS/ros_lib/topic_tools/DemuxSelect.h \
    $$PWD/ROS/ros_lib/topic_tools/MuxAdd.h \
    $$PWD/ROS/ros_lib/topic_tools/MuxDelete.h \
    $$PWD/ROS/ros_lib/topic_tools/MuxList.h \
    $$PWD/ROS/ros_lib/topic_tools/MuxSelect.h \
    $$PWD/ROS/ros_lib/trajectory_msgs/JointTrajectory.h \
    $$PWD/ROS/ros_lib/trajectory_msgs/JointTrajectoryPoint.h \
    $$PWD/ROS/ros_lib/trajectory_msgs/MultiDOFJointTrajectory.h \
    $$PWD/ROS/ros_lib/trajectory_msgs/MultiDOFJointTrajectoryPoint.h \
    $$PWD/ROS/ros_lib/turtle_actionlib/ShapeAction.h \
    $$PWD/ROS/ros_lib/turtle_actionlib/ShapeActionFeedback.h \
    $$PWD/ROS/ros_lib/turtle_actionlib/ShapeActionGoal.h \
    $$PWD/ROS/ros_lib/turtle_actionlib/ShapeActionResult.h \
    $$PWD/ROS/ros_lib/turtle_actionlib/ShapeFeedback.h \
    $$PWD/ROS/ros_lib/turtle_actionlib/ShapeGoal.h \
    $$PWD/ROS/ros_lib/turtle_actionlib/ShapeResult.h \
    $$PWD/ROS/ros_lib/turtle_actionlib/Velocity.h \
    $$PWD/ROS/ros_lib/turtlesim/Color.h \
    $$PWD/ROS/ros_lib/turtlesim/Kill.h \
    $$PWD/ROS/ros_lib/turtlesim/Pose.h \
    $$PWD/ROS/ros_lib/turtlesim/SetPen.h \
    $$PWD/ROS/ros_lib/turtlesim/Spawn.h \
    $$PWD/ROS/ros_lib/turtlesim/TeleportAbsolute.h \
    $$PWD/ROS/ros_lib/turtlesim/TeleportRelative.h \
    $$PWD/ROS/ros_lib/visualization_msgs/ImageMarker.h \
    $$PWD/ROS/ros_lib/visualization_msgs/InteractiveMarker.h \
    $$PWD/ROS/ros_lib/visualization_msgs/InteractiveMarkerControl.h \
    $$PWD/ROS/ros_lib/visualization_msgs/InteractiveMarkerFeedback.h \
    $$PWD/ROS/ros_lib/visualization_msgs/InteractiveMarkerInit.h \
    $$PWD/ROS/ros_lib/visualization_msgs/InteractiveMarkerPose.h \
    $$PWD/ROS/ros_lib/visualization_msgs/InteractiveMarkerUpdate.h \
    $$PWD/ROS/ros_lib/visualization_msgs/Marker.h \
    $$PWD/ROS/ros_lib/visualization_msgs/MarkerArray.h \
    $$PWD/ROS/ros_lib/visualization_msgs/MenuEntry.h \
    $$PWD/ROSComManger.h \
    $$PWD/WindowsSocketClient.h

SOURCES += \
    $$PWD/ComThread.cpp \
    $$PWD/ROS/ros_lib/duration.cpp \
    $$PWD/ROS/ros_lib/time.cpp \
    $$PWD/ROSComManger.cpp \
    $$PWD/WindowsSocketClient.cpp

